// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztolwrwcnglbfzdqttrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0b2x3cndjbmdsYmZ6ZHF0dHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNDg1MzIsImV4cCI6MjA0ODgyNDUzMn0.7LGgqnHDooXxQ76huK1BY4TMBUmegXx2xUCpHEBgJwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);